config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :notes, only: [:create, :destroy]
  get "home/index"
  get "shuffle", to: "home#shuffle"
  get "toast", to: "home#toast"
  get "qoute", to: "home#qoute"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  scope :actived, -> { where(actived: true)}

  def self.implicit_order_column
    "created_at"
  end
end

app/models/qoute.rb
class Qoute
  attr_accessor :originator, :content

  def initialize(content:, originator:)
    @content = content
    @originator = originator
  end
end

app/models/qoutes_generator.rb
require "http"
require "json"

class QoutesGenerator
  def initialize
    @url = "https://quotes15.p.rapidapi.com/quotes/random/"
  end

  def random
    ctx = OpenSSL::SSL::SSLContext.new
    ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE

    response = HTTP.headers({
      "X-RapidAPI-Key": ENV["RAPID_API_KEY"],
      "X-RapidAPI-Host": ENV["RAPID_API_HOST"]
    }).get(@url, ssl_context: ctx)
    if response.status.success?
      body = JSON.parse(response.body).with_indifferent_access
      Qoute.new(content: body[:content], originator: body[:originator][:name])
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
    @exception = request.env["action_dispatch.exception"]
    @status_code = 
      @exception.try(:status_code) ||
        ActionDispatch::ExceptionWrapper.new(
        request.env, @exception
      ).status_code

    render view_for_code(@status_code), status: @status_code
  end

  private
    def view_for_code(code)
      supported_error_codes.fetch(code, "404")
    end

    def supported_error_codes
      {
        400 => "400",
        403 => "403",
        404 => "404",
        500 => "500"
      }
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @notes = Note.actived.order(created_at: :desc).limit(30)
    @note = Note.new
  end

  def toast = nil

  def shuffle
    @qoute = QoutesGenerator.new.random
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.order(created_at: :desc).actived
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        @notes = Note.actived.order(created_at: :desc).limit(30)
        format.turbo_stream
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      @notes = Note.actived.order(created_at: :desc).limit(30)
      format.turbo_stream
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.fetch(:note, {}).permit(:message, :from_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dispatch_event_helper.rb
module DispatchEventHelper
  def dispatch_event(name)
    turbo_stream_action_tag :dispatch_event, name: name
  end
end

Turbo::Streams::TagBuilder.prepend(DispatchEventHelper)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/index.html.erb
<%= turbo_frame_tag "toast", src: "/toast", loading: "lazy" %>
<h2 class="font-bold font-serif text-3xl text-center text-green-400 py-4">Notes</h2>

<%= turbo_frame_tag "note_form", class: "w-full md:2/3 lg:w-1/2 mx-auto" do %>
  <%= render "notes/form", note: @note %>
<% end %>

<%= render NotesComponent.new notes: @notes %>

app/views/home/qoute.html.erb
<%= link_to 'Shuffle Qoute', shuffle_path, class: "rounded-full bg-red-400 text-white text-center px-3 py-2 w-48 ", data: { turbo_stream: true } %>

<div id="qoute-content" class="py-4 font-bold text-3xl"></div>
<span id="qoute-originator" class="py-2 text-gray-500"></span>

<script content="module">
  window.addEventListener("qoute", (event) => {
    alert("Received `qoute` event from turbo stream actions")
  })
</script>

app/views/home/shuffle.turbo_stream.erb
<%= turbo_stream.update "qoute-content", @qoute.content %>
<%= turbo_stream.update "qoute-originator", @qoute.originator %>

app/views/home/toast.html.erb
<%= turbo_frame_tag "toast" do %>
  <%= render ToastComponent.new %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlyPhlexWired</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script async defer data-domain="fly-phlex-wired.fly.dev" src="https://analytics.karn.work/js/plausible.js"></script>
  </head>

  <body>
    <%= render NavbarComponent.new %>
    <main class="container mx-auto py-12 px-5 flex flex-col relative">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlyPhlexWired</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script async defer data-domain="fly-phlex-wired.fly.dev" src="https://analytics.karn.work/js/plausible.js"></script>
  </head>

  <body>
    <main class="container mx-auto py-12 px-5 flex flex-col relative">
      <%= yield %>
    </main>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, data: { controller: "spinner" }, class: "flex flex-col p-2") do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col py-2">
    <%= form.label :message, class: "font-bold text-lg" %>
    <%= form.text_field "message", maxlength: 60, class: "rounded-lg border focus:border-purple-500 focus:outline-none p-2 break-words", autocomplete: "off", required: true %>
  </div>

  <div class="flex flex-col py-2">
    <%= form.label :from_user, class: "font-bold text-lg" %>
    <%= form.text_field "from_user", maxlength: 60, class: "rounded-lg border focus:border-purple-500 focus:outline-none p-2 break-words", autocomplete: "off", required: true %>
  </div>

  <div class="flex justify-center p-2">
    <button type="submit" class="rounded-lg bg-purple-300 text-white px-4 py-2 w-fit inline-flex items-center">
      <span>Save</span>
    </button>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>" class="mx-auto rounded-lg border p-4 w-full flex flex-col gap-y-2 my-4">
  <div class="flex justify-end">
    <%= button_to "Close", note_path(note), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' }}, class: "rounded-full bg-red-400 text-white text-sm px-3 py-2" %>
  </div>
  <div class="flex flex-col">
    <h4 class="text-xs font-bold text-gray-400">Message</h4>
    <div class="text-lg"><%= note.message %></div>
  </div>
  <div class="flex flex-col">
    <h4 class="text-xs font-bold text-gray-400">From</h4>
    <div class="text-lg"><%= note.from_user %></div>
  </div>
  <div class="flex flex-col">
    <h4 class="text-xs font-bold text-gray-400">When</h4>
    <div class="text-lg"><%= time_ago_in_words note.created_at %></div>
  </div>
</div>

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.replace "note_form" do %>
  <%= turbo_frame_tag "note_form", class: "w-full md:2/3 lg:w-1/2 mx-auto" do %>
    <%= render "notes/form", note: Note.new %>
  <% end %>
<% end %>

<%= turbo_stream.replace "notes" do %>
  <%= render NotesComponent.new notes: @notes %>
<% end %>

app/views/notes/destroy.turbo_stream.erb
<%= turbo_stream.replace "notes" do %>
  <%= render NotesComponent.new notes: @notes %>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notes</h1>

<div id="notes">
  <% @notes.each do |note| %>
    <%= render note %>
  <% end %>
</div>

<%= link_to "New note", new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
</div>